// <auto-generated />
namespace MediationApplication.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class mantras1 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(mantras1));
        
        string IMigrationMetadata.Id
        {
            get { return "202105292021252_mantras1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
