// <auto-generated />
namespace MediationApplication.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class mantra_category_validation : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(mantra_category_validation));
        
        string IMigrationMetadata.Id
        {
            get { return "202108061850244_mantra_category_validation"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
