// <auto-generated />
namespace MediationApplication.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class journalentrymeditationsession : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(journalentrymeditationsession));
        
        string IMigrationMetadata.Id
        {
            get { return "202105292134238_journalentry-meditationsession"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
